name: Docker Build (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - "infra/docker/**"

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build Backend Image
        run: docker build -t sadaqa-backend:latest -f infra/docker/backend/Dockerfile.backend .
      - name: Build Frontend Image
        run: docker build -t sadaqa-frontend:latest -f infra/docker/frontend/Dockerfile.frontend .
      - name: Build Simulator Image
        run: docker build -t sadaqa-simulator:latest -f infra/docker/Dockerfile.simulator .
